# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.20.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.20.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/gofmane/42/webserv-charleamb

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/gofmane/42/webserv-charleamb

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.20.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.20.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gofmane/42/webserv-charleamb/CMakeFiles /Users/gofmane/42/webserv-charleamb//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gofmane/42/webserv-charleamb/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named webserv

# Build rule for target.
webserv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 webserv
.PHONY : webserv

# fast build rule for target.
webserv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/build
.PHONY : webserv/fast

src/Networking/Client/Client.o: src/Networking/Client/Client.cpp.o
.PHONY : src/Networking/Client/Client.o

# target to build an object file
src/Networking/Client/Client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Client/Client.cpp.o
.PHONY : src/Networking/Client/Client.cpp.o

src/Networking/Client/Client.i: src/Networking/Client/Client.cpp.i
.PHONY : src/Networking/Client/Client.i

# target to preprocess a source file
src/Networking/Client/Client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Client/Client.cpp.i
.PHONY : src/Networking/Client/Client.cpp.i

src/Networking/Client/Client.s: src/Networking/Client/Client.cpp.s
.PHONY : src/Networking/Client/Client.s

# target to generate assembly for a file
src/Networking/Client/Client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Client/Client.cpp.s
.PHONY : src/Networking/Client/Client.cpp.s

src/Networking/Response/Response.o: src/Networking/Response/Response.cpp.o
.PHONY : src/Networking/Response/Response.o

# target to build an object file
src/Networking/Response/Response.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Response/Response.cpp.o
.PHONY : src/Networking/Response/Response.cpp.o

src/Networking/Response/Response.i: src/Networking/Response/Response.cpp.i
.PHONY : src/Networking/Response/Response.i

# target to preprocess a source file
src/Networking/Response/Response.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Response/Response.cpp.i
.PHONY : src/Networking/Response/Response.cpp.i

src/Networking/Response/Response.s: src/Networking/Response/Response.cpp.s
.PHONY : src/Networking/Response/Response.s

# target to generate assembly for a file
src/Networking/Response/Response.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Response/Response.cpp.s
.PHONY : src/Networking/Response/Response.cpp.s

src/Networking/Response/ResponseHeader.o: src/Networking/Response/ResponseHeader.cpp.o
.PHONY : src/Networking/Response/ResponseHeader.o

# target to build an object file
src/Networking/Response/ResponseHeader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Response/ResponseHeader.cpp.o
.PHONY : src/Networking/Response/ResponseHeader.cpp.o

src/Networking/Response/ResponseHeader.i: src/Networking/Response/ResponseHeader.cpp.i
.PHONY : src/Networking/Response/ResponseHeader.i

# target to preprocess a source file
src/Networking/Response/ResponseHeader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Response/ResponseHeader.cpp.i
.PHONY : src/Networking/Response/ResponseHeader.cpp.i

src/Networking/Response/ResponseHeader.s: src/Networking/Response/ResponseHeader.cpp.s
.PHONY : src/Networking/Response/ResponseHeader.s

# target to generate assembly for a file
src/Networking/Response/ResponseHeader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Response/ResponseHeader.cpp.s
.PHONY : src/Networking/Response/ResponseHeader.cpp.s

src/Networking/Server/Server.o: src/Networking/Server/Server.cpp.o
.PHONY : src/Networking/Server/Server.o

# target to build an object file
src/Networking/Server/Server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Server/Server.cpp.o
.PHONY : src/Networking/Server/Server.cpp.o

src/Networking/Server/Server.i: src/Networking/Server/Server.cpp.i
.PHONY : src/Networking/Server/Server.i

# target to preprocess a source file
src/Networking/Server/Server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Server/Server.cpp.i
.PHONY : src/Networking/Server/Server.cpp.i

src/Networking/Server/Server.s: src/Networking/Server/Server.cpp.s
.PHONY : src/Networking/Server/Server.s

# target to generate assembly for a file
src/Networking/Server/Server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Server/Server.cpp.s
.PHONY : src/Networking/Server/Server.cpp.s

src/Networking/Sockets/BindingSocket.o: src/Networking/Sockets/BindingSocket.cpp.o
.PHONY : src/Networking/Sockets/BindingSocket.o

# target to build an object file
src/Networking/Sockets/BindingSocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Sockets/BindingSocket.cpp.o
.PHONY : src/Networking/Sockets/BindingSocket.cpp.o

src/Networking/Sockets/BindingSocket.i: src/Networking/Sockets/BindingSocket.cpp.i
.PHONY : src/Networking/Sockets/BindingSocket.i

# target to preprocess a source file
src/Networking/Sockets/BindingSocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Sockets/BindingSocket.cpp.i
.PHONY : src/Networking/Sockets/BindingSocket.cpp.i

src/Networking/Sockets/BindingSocket.s: src/Networking/Sockets/BindingSocket.cpp.s
.PHONY : src/Networking/Sockets/BindingSocket.s

# target to generate assembly for a file
src/Networking/Sockets/BindingSocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Sockets/BindingSocket.cpp.s
.PHONY : src/Networking/Sockets/BindingSocket.cpp.s

src/Networking/Sockets/ListeningSocket.o: src/Networking/Sockets/ListeningSocket.cpp.o
.PHONY : src/Networking/Sockets/ListeningSocket.o

# target to build an object file
src/Networking/Sockets/ListeningSocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Sockets/ListeningSocket.cpp.o
.PHONY : src/Networking/Sockets/ListeningSocket.cpp.o

src/Networking/Sockets/ListeningSocket.i: src/Networking/Sockets/ListeningSocket.cpp.i
.PHONY : src/Networking/Sockets/ListeningSocket.i

# target to preprocess a source file
src/Networking/Sockets/ListeningSocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Sockets/ListeningSocket.cpp.i
.PHONY : src/Networking/Sockets/ListeningSocket.cpp.i

src/Networking/Sockets/ListeningSocket.s: src/Networking/Sockets/ListeningSocket.cpp.s
.PHONY : src/Networking/Sockets/ListeningSocket.s

# target to generate assembly for a file
src/Networking/Sockets/ListeningSocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Sockets/ListeningSocket.cpp.s
.PHONY : src/Networking/Sockets/ListeningSocket.cpp.s

src/Networking/Sockets/Socket.o: src/Networking/Sockets/Socket.cpp.o
.PHONY : src/Networking/Sockets/Socket.o

# target to build an object file
src/Networking/Sockets/Socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Sockets/Socket.cpp.o
.PHONY : src/Networking/Sockets/Socket.cpp.o

src/Networking/Sockets/Socket.i: src/Networking/Sockets/Socket.cpp.i
.PHONY : src/Networking/Sockets/Socket.i

# target to preprocess a source file
src/Networking/Sockets/Socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Sockets/Socket.cpp.i
.PHONY : src/Networking/Sockets/Socket.cpp.i

src/Networking/Sockets/Socket.s: src/Networking/Sockets/Socket.cpp.s
.PHONY : src/Networking/Sockets/Socket.s

# target to generate assembly for a file
src/Networking/Sockets/Socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Sockets/Socket.cpp.s
.PHONY : src/Networking/Sockets/Socket.cpp.s

src/Networking/Status/Status.o: src/Networking/Status/Status.cpp.o
.PHONY : src/Networking/Status/Status.o

# target to build an object file
src/Networking/Status/Status.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Status/Status.cpp.o
.PHONY : src/Networking/Status/Status.cpp.o

src/Networking/Status/Status.i: src/Networking/Status/Status.cpp.i
.PHONY : src/Networking/Status/Status.i

# target to preprocess a source file
src/Networking/Status/Status.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Status/Status.cpp.i
.PHONY : src/Networking/Status/Status.cpp.i

src/Networking/Status/Status.s: src/Networking/Status/Status.cpp.s
.PHONY : src/Networking/Status/Status.s

# target to generate assembly for a file
src/Networking/Status/Status.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Status/Status.cpp.s
.PHONY : src/Networking/Status/Status.cpp.s

src/Networking/Utils/utils.o: src/Networking/Utils/utils.cpp.o
.PHONY : src/Networking/Utils/utils.o

# target to build an object file
src/Networking/Utils/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Utils/utils.cpp.o
.PHONY : src/Networking/Utils/utils.cpp.o

src/Networking/Utils/utils.i: src/Networking/Utils/utils.cpp.i
.PHONY : src/Networking/Utils/utils.i

# target to preprocess a source file
src/Networking/Utils/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Utils/utils.cpp.i
.PHONY : src/Networking/Utils/utils.cpp.i

src/Networking/Utils/utils.s: src/Networking/Utils/utils.cpp.s
.PHONY : src/Networking/Utils/utils.s

# target to generate assembly for a file
src/Networking/Utils/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/Networking/Utils/utils.cpp.s
.PHONY : src/Networking/Utils/utils.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/parser/Error.o: src/parser/Error.cpp.o
.PHONY : src/parser/Error.o

# target to build an object file
src/parser/Error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/Error.cpp.o
.PHONY : src/parser/Error.cpp.o

src/parser/Error.i: src/parser/Error.cpp.i
.PHONY : src/parser/Error.i

# target to preprocess a source file
src/parser/Error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/Error.cpp.i
.PHONY : src/parser/Error.cpp.i

src/parser/Error.s: src/parser/Error.cpp.s
.PHONY : src/parser/Error.s

# target to generate assembly for a file
src/parser/Error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/Error.cpp.s
.PHONY : src/parser/Error.cpp.s

src/parser/bytes/Alpha.o: src/parser/bytes/Alpha.cpp.o
.PHONY : src/parser/bytes/Alpha.o

# target to build an object file
src/parser/bytes/Alpha.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/Alpha.cpp.o
.PHONY : src/parser/bytes/Alpha.cpp.o

src/parser/bytes/Alpha.i: src/parser/bytes/Alpha.cpp.i
.PHONY : src/parser/bytes/Alpha.i

# target to preprocess a source file
src/parser/bytes/Alpha.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/Alpha.cpp.i
.PHONY : src/parser/bytes/Alpha.cpp.i

src/parser/bytes/Alpha.s: src/parser/bytes/Alpha.cpp.s
.PHONY : src/parser/bytes/Alpha.s

# target to generate assembly for a file
src/parser/bytes/Alpha.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/Alpha.cpp.s
.PHONY : src/parser/bytes/Alpha.cpp.s

src/parser/bytes/Char.o: src/parser/bytes/Char.cpp.o
.PHONY : src/parser/bytes/Char.o

# target to build an object file
src/parser/bytes/Char.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/Char.cpp.o
.PHONY : src/parser/bytes/Char.cpp.o

src/parser/bytes/Char.i: src/parser/bytes/Char.cpp.i
.PHONY : src/parser/bytes/Char.i

# target to preprocess a source file
src/parser/bytes/Char.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/Char.cpp.i
.PHONY : src/parser/bytes/Char.cpp.i

src/parser/bytes/Char.s: src/parser/bytes/Char.cpp.s
.PHONY : src/parser/bytes/Char.s

# target to generate assembly for a file
src/parser/bytes/Char.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/Char.cpp.s
.PHONY : src/parser/bytes/Char.cpp.s

src/parser/bytes/Digit.o: src/parser/bytes/Digit.cpp.o
.PHONY : src/parser/bytes/Digit.o

# target to build an object file
src/parser/bytes/Digit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/Digit.cpp.o
.PHONY : src/parser/bytes/Digit.cpp.o

src/parser/bytes/Digit.i: src/parser/bytes/Digit.cpp.i
.PHONY : src/parser/bytes/Digit.i

# target to preprocess a source file
src/parser/bytes/Digit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/Digit.cpp.i
.PHONY : src/parser/bytes/Digit.cpp.i

src/parser/bytes/Digit.s: src/parser/bytes/Digit.cpp.s
.PHONY : src/parser/bytes/Digit.s

# target to generate assembly for a file
src/parser/bytes/Digit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/Digit.cpp.s
.PHONY : src/parser/bytes/Digit.cpp.s

src/parser/bytes/HexChar.o: src/parser/bytes/HexChar.cpp.o
.PHONY : src/parser/bytes/HexChar.o

# target to build an object file
src/parser/bytes/HexChar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/HexChar.cpp.o
.PHONY : src/parser/bytes/HexChar.cpp.o

src/parser/bytes/HexChar.i: src/parser/bytes/HexChar.cpp.i
.PHONY : src/parser/bytes/HexChar.i

# target to preprocess a source file
src/parser/bytes/HexChar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/HexChar.cpp.i
.PHONY : src/parser/bytes/HexChar.cpp.i

src/parser/bytes/HexChar.s: src/parser/bytes/HexChar.cpp.s
.PHONY : src/parser/bytes/HexChar.s

# target to generate assembly for a file
src/parser/bytes/HexChar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/HexChar.cpp.s
.PHONY : src/parser/bytes/HexChar.cpp.s

src/parser/bytes/ITag.o: src/parser/bytes/ITag.cpp.o
.PHONY : src/parser/bytes/ITag.o

# target to build an object file
src/parser/bytes/ITag.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/ITag.cpp.o
.PHONY : src/parser/bytes/ITag.cpp.o

src/parser/bytes/ITag.i: src/parser/bytes/ITag.cpp.i
.PHONY : src/parser/bytes/ITag.i

# target to preprocess a source file
src/parser/bytes/ITag.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/ITag.cpp.i
.PHONY : src/parser/bytes/ITag.cpp.i

src/parser/bytes/ITag.s: src/parser/bytes/ITag.cpp.s
.PHONY : src/parser/bytes/ITag.s

# target to generate assembly for a file
src/parser/bytes/ITag.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/ITag.cpp.s
.PHONY : src/parser/bytes/ITag.cpp.s

src/parser/bytes/Match.o: src/parser/bytes/Match.cpp.o
.PHONY : src/parser/bytes/Match.o

# target to build an object file
src/parser/bytes/Match.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/Match.cpp.o
.PHONY : src/parser/bytes/Match.cpp.o

src/parser/bytes/Match.i: src/parser/bytes/Match.cpp.i
.PHONY : src/parser/bytes/Match.i

# target to preprocess a source file
src/parser/bytes/Match.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/Match.cpp.i
.PHONY : src/parser/bytes/Match.cpp.i

src/parser/bytes/Match.s: src/parser/bytes/Match.cpp.s
.PHONY : src/parser/bytes/Match.s

# target to generate assembly for a file
src/parser/bytes/Match.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/Match.cpp.s
.PHONY : src/parser/bytes/Match.cpp.s

src/parser/bytes/OneOf.o: src/parser/bytes/OneOf.cpp.o
.PHONY : src/parser/bytes/OneOf.o

# target to build an object file
src/parser/bytes/OneOf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/OneOf.cpp.o
.PHONY : src/parser/bytes/OneOf.cpp.o

src/parser/bytes/OneOf.i: src/parser/bytes/OneOf.cpp.i
.PHONY : src/parser/bytes/OneOf.i

# target to preprocess a source file
src/parser/bytes/OneOf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/OneOf.cpp.i
.PHONY : src/parser/bytes/OneOf.cpp.i

src/parser/bytes/OneOf.s: src/parser/bytes/OneOf.cpp.s
.PHONY : src/parser/bytes/OneOf.s

# target to generate assembly for a file
src/parser/bytes/OneOf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/OneOf.cpp.s
.PHONY : src/parser/bytes/OneOf.cpp.s

src/parser/bytes/Tag.o: src/parser/bytes/Tag.cpp.o
.PHONY : src/parser/bytes/Tag.o

# target to build an object file
src/parser/bytes/Tag.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/Tag.cpp.o
.PHONY : src/parser/bytes/Tag.cpp.o

src/parser/bytes/Tag.i: src/parser/bytes/Tag.cpp.i
.PHONY : src/parser/bytes/Tag.i

# target to preprocess a source file
src/parser/bytes/Tag.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/Tag.cpp.i
.PHONY : src/parser/bytes/Tag.cpp.i

src/parser/bytes/Tag.s: src/parser/bytes/Tag.cpp.s
.PHONY : src/parser/bytes/Tag.s

# target to generate assembly for a file
src/parser/bytes/Tag.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/Tag.cpp.s
.PHONY : src/parser/bytes/Tag.cpp.s

src/parser/bytes/TakeUntil.o: src/parser/bytes/TakeUntil.cpp.o
.PHONY : src/parser/bytes/TakeUntil.o

# target to build an object file
src/parser/bytes/TakeUntil.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/TakeUntil.cpp.o
.PHONY : src/parser/bytes/TakeUntil.cpp.o

src/parser/bytes/TakeUntil.i: src/parser/bytes/TakeUntil.cpp.i
.PHONY : src/parser/bytes/TakeUntil.i

# target to preprocess a source file
src/parser/bytes/TakeUntil.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/TakeUntil.cpp.i
.PHONY : src/parser/bytes/TakeUntil.cpp.i

src/parser/bytes/TakeUntil.s: src/parser/bytes/TakeUntil.cpp.s
.PHONY : src/parser/bytes/TakeUntil.s

# target to generate assembly for a file
src/parser/bytes/TakeUntil.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/TakeUntil.cpp.s
.PHONY : src/parser/bytes/TakeUntil.cpp.s

src/parser/bytes/TakeWhile.o: src/parser/bytes/TakeWhile.cpp.o
.PHONY : src/parser/bytes/TakeWhile.o

# target to build an object file
src/parser/bytes/TakeWhile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/TakeWhile.cpp.o
.PHONY : src/parser/bytes/TakeWhile.cpp.o

src/parser/bytes/TakeWhile.i: src/parser/bytes/TakeWhile.cpp.i
.PHONY : src/parser/bytes/TakeWhile.i

# target to preprocess a source file
src/parser/bytes/TakeWhile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/TakeWhile.cpp.i
.PHONY : src/parser/bytes/TakeWhile.cpp.i

src/parser/bytes/TakeWhile.s: src/parser/bytes/TakeWhile.cpp.s
.PHONY : src/parser/bytes/TakeWhile.s

# target to generate assembly for a file
src/parser/bytes/TakeWhile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parser/bytes/TakeWhile.cpp.s
.PHONY : src/parser/bytes/TakeWhile.cpp.s

src/parsing/Config/Module/Cgi.o: src/parsing/Config/Module/Cgi.cpp.o
.PHONY : src/parsing/Config/Module/Cgi.o

# target to build an object file
src/parsing/Config/Module/Cgi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/Cgi.cpp.o
.PHONY : src/parsing/Config/Module/Cgi.cpp.o

src/parsing/Config/Module/Cgi.i: src/parsing/Config/Module/Cgi.cpp.i
.PHONY : src/parsing/Config/Module/Cgi.i

# target to preprocess a source file
src/parsing/Config/Module/Cgi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/Cgi.cpp.i
.PHONY : src/parsing/Config/Module/Cgi.cpp.i

src/parsing/Config/Module/Cgi.s: src/parsing/Config/Module/Cgi.cpp.s
.PHONY : src/parsing/Config/Module/Cgi.s

# target to generate assembly for a file
src/parsing/Config/Module/Cgi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/Cgi.cpp.s
.PHONY : src/parsing/Config/Module/Cgi.cpp.s

src/parsing/Config/Module/ClientMaxBodySize.o: src/parsing/Config/Module/ClientMaxBodySize.cpp.o
.PHONY : src/parsing/Config/Module/ClientMaxBodySize.o

# target to build an object file
src/parsing/Config/Module/ClientMaxBodySize.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/ClientMaxBodySize.cpp.o
.PHONY : src/parsing/Config/Module/ClientMaxBodySize.cpp.o

src/parsing/Config/Module/ClientMaxBodySize.i: src/parsing/Config/Module/ClientMaxBodySize.cpp.i
.PHONY : src/parsing/Config/Module/ClientMaxBodySize.i

# target to preprocess a source file
src/parsing/Config/Module/ClientMaxBodySize.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/ClientMaxBodySize.cpp.i
.PHONY : src/parsing/Config/Module/ClientMaxBodySize.cpp.i

src/parsing/Config/Module/ClientMaxBodySize.s: src/parsing/Config/Module/ClientMaxBodySize.cpp.s
.PHONY : src/parsing/Config/Module/ClientMaxBodySize.s

# target to generate assembly for a file
src/parsing/Config/Module/ClientMaxBodySize.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/ClientMaxBodySize.cpp.s
.PHONY : src/parsing/Config/Module/ClientMaxBodySize.cpp.s

src/parsing/Config/Module/ErrorPage.o: src/parsing/Config/Module/ErrorPage.cpp.o
.PHONY : src/parsing/Config/Module/ErrorPage.o

# target to build an object file
src/parsing/Config/Module/ErrorPage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/ErrorPage.cpp.o
.PHONY : src/parsing/Config/Module/ErrorPage.cpp.o

src/parsing/Config/Module/ErrorPage.i: src/parsing/Config/Module/ErrorPage.cpp.i
.PHONY : src/parsing/Config/Module/ErrorPage.i

# target to preprocess a source file
src/parsing/Config/Module/ErrorPage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/ErrorPage.cpp.i
.PHONY : src/parsing/Config/Module/ErrorPage.cpp.i

src/parsing/Config/Module/ErrorPage.s: src/parsing/Config/Module/ErrorPage.cpp.s
.PHONY : src/parsing/Config/Module/ErrorPage.s

# target to generate assembly for a file
src/parsing/Config/Module/ErrorPage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/ErrorPage.cpp.s
.PHONY : src/parsing/Config/Module/ErrorPage.cpp.s

src/parsing/Config/Module/Index.o: src/parsing/Config/Module/Index.cpp.o
.PHONY : src/parsing/Config/Module/Index.o

# target to build an object file
src/parsing/Config/Module/Index.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/Index.cpp.o
.PHONY : src/parsing/Config/Module/Index.cpp.o

src/parsing/Config/Module/Index.i: src/parsing/Config/Module/Index.cpp.i
.PHONY : src/parsing/Config/Module/Index.i

# target to preprocess a source file
src/parsing/Config/Module/Index.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/Index.cpp.i
.PHONY : src/parsing/Config/Module/Index.cpp.i

src/parsing/Config/Module/Index.s: src/parsing/Config/Module/Index.cpp.s
.PHONY : src/parsing/Config/Module/Index.s

# target to generate assembly for a file
src/parsing/Config/Module/Index.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/Index.cpp.s
.PHONY : src/parsing/Config/Module/Index.cpp.s

src/parsing/Config/Module/Listen.o: src/parsing/Config/Module/Listen.cpp.o
.PHONY : src/parsing/Config/Module/Listen.o

# target to build an object file
src/parsing/Config/Module/Listen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/Listen.cpp.o
.PHONY : src/parsing/Config/Module/Listen.cpp.o

src/parsing/Config/Module/Listen.i: src/parsing/Config/Module/Listen.cpp.i
.PHONY : src/parsing/Config/Module/Listen.i

# target to preprocess a source file
src/parsing/Config/Module/Listen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/Listen.cpp.i
.PHONY : src/parsing/Config/Module/Listen.cpp.i

src/parsing/Config/Module/Listen.s: src/parsing/Config/Module/Listen.cpp.s
.PHONY : src/parsing/Config/Module/Listen.s

# target to generate assembly for a file
src/parsing/Config/Module/Listen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/Listen.cpp.s
.PHONY : src/parsing/Config/Module/Listen.cpp.s

src/parsing/Config/Module/Location.o: src/parsing/Config/Module/Location.cpp.o
.PHONY : src/parsing/Config/Module/Location.o

# target to build an object file
src/parsing/Config/Module/Location.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/Location.cpp.o
.PHONY : src/parsing/Config/Module/Location.cpp.o

src/parsing/Config/Module/Location.i: src/parsing/Config/Module/Location.cpp.i
.PHONY : src/parsing/Config/Module/Location.i

# target to preprocess a source file
src/parsing/Config/Module/Location.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/Location.cpp.i
.PHONY : src/parsing/Config/Module/Location.cpp.i

src/parsing/Config/Module/Location.s: src/parsing/Config/Module/Location.cpp.s
.PHONY : src/parsing/Config/Module/Location.s

# target to generate assembly for a file
src/parsing/Config/Module/Location.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/Location.cpp.s
.PHONY : src/parsing/Config/Module/Location.cpp.s

src/parsing/Config/Module/Methods.o: src/parsing/Config/Module/Methods.cpp.o
.PHONY : src/parsing/Config/Module/Methods.o

# target to build an object file
src/parsing/Config/Module/Methods.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/Methods.cpp.o
.PHONY : src/parsing/Config/Module/Methods.cpp.o

src/parsing/Config/Module/Methods.i: src/parsing/Config/Module/Methods.cpp.i
.PHONY : src/parsing/Config/Module/Methods.i

# target to preprocess a source file
src/parsing/Config/Module/Methods.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/Methods.cpp.i
.PHONY : src/parsing/Config/Module/Methods.cpp.i

src/parsing/Config/Module/Methods.s: src/parsing/Config/Module/Methods.cpp.s
.PHONY : src/parsing/Config/Module/Methods.s

# target to generate assembly for a file
src/parsing/Config/Module/Methods.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/Methods.cpp.s
.PHONY : src/parsing/Config/Module/Methods.cpp.s

src/parsing/Config/Module/Redirect.o: src/parsing/Config/Module/Redirect.cpp.o
.PHONY : src/parsing/Config/Module/Redirect.o

# target to build an object file
src/parsing/Config/Module/Redirect.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/Redirect.cpp.o
.PHONY : src/parsing/Config/Module/Redirect.cpp.o

src/parsing/Config/Module/Redirect.i: src/parsing/Config/Module/Redirect.cpp.i
.PHONY : src/parsing/Config/Module/Redirect.i

# target to preprocess a source file
src/parsing/Config/Module/Redirect.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/Redirect.cpp.i
.PHONY : src/parsing/Config/Module/Redirect.cpp.i

src/parsing/Config/Module/Redirect.s: src/parsing/Config/Module/Redirect.cpp.s
.PHONY : src/parsing/Config/Module/Redirect.s

# target to generate assembly for a file
src/parsing/Config/Module/Redirect.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/Redirect.cpp.s
.PHONY : src/parsing/Config/Module/Redirect.cpp.s

src/parsing/Config/Module/Root.o: src/parsing/Config/Module/Root.cpp.o
.PHONY : src/parsing/Config/Module/Root.o

# target to build an object file
src/parsing/Config/Module/Root.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/Root.cpp.o
.PHONY : src/parsing/Config/Module/Root.cpp.o

src/parsing/Config/Module/Root.i: src/parsing/Config/Module/Root.cpp.i
.PHONY : src/parsing/Config/Module/Root.i

# target to preprocess a source file
src/parsing/Config/Module/Root.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/Root.cpp.i
.PHONY : src/parsing/Config/Module/Root.cpp.i

src/parsing/Config/Module/Root.s: src/parsing/Config/Module/Root.cpp.s
.PHONY : src/parsing/Config/Module/Root.s

# target to generate assembly for a file
src/parsing/Config/Module/Root.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/Root.cpp.s
.PHONY : src/parsing/Config/Module/Root.cpp.s

src/parsing/Config/Module/ServerName.o: src/parsing/Config/Module/ServerName.cpp.o
.PHONY : src/parsing/Config/Module/ServerName.o

# target to build an object file
src/parsing/Config/Module/ServerName.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/ServerName.cpp.o
.PHONY : src/parsing/Config/Module/ServerName.cpp.o

src/parsing/Config/Module/ServerName.i: src/parsing/Config/Module/ServerName.cpp.i
.PHONY : src/parsing/Config/Module/ServerName.i

# target to preprocess a source file
src/parsing/Config/Module/ServerName.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/ServerName.cpp.i
.PHONY : src/parsing/Config/Module/ServerName.cpp.i

src/parsing/Config/Module/ServerName.s: src/parsing/Config/Module/ServerName.cpp.s
.PHONY : src/parsing/Config/Module/ServerName.s

# target to generate assembly for a file
src/parsing/Config/Module/ServerName.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/ServerName.cpp.s
.PHONY : src/parsing/Config/Module/ServerName.cpp.s

src/parsing/Config/Module/Upload.o: src/parsing/Config/Module/Upload.cpp.o
.PHONY : src/parsing/Config/Module/Upload.o

# target to build an object file
src/parsing/Config/Module/Upload.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/Upload.cpp.o
.PHONY : src/parsing/Config/Module/Upload.cpp.o

src/parsing/Config/Module/Upload.i: src/parsing/Config/Module/Upload.cpp.i
.PHONY : src/parsing/Config/Module/Upload.i

# target to preprocess a source file
src/parsing/Config/Module/Upload.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/Upload.cpp.i
.PHONY : src/parsing/Config/Module/Upload.cpp.i

src/parsing/Config/Module/Upload.s: src/parsing/Config/Module/Upload.cpp.s
.PHONY : src/parsing/Config/Module/Upload.s

# target to generate assembly for a file
src/parsing/Config/Module/Upload.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Module/Upload.cpp.s
.PHONY : src/parsing/Config/Module/Upload.cpp.s

src/parsing/Config/Structure/Line.o: src/parsing/Config/Structure/Line.cpp.o
.PHONY : src/parsing/Config/Structure/Line.o

# target to build an object file
src/parsing/Config/Structure/Line.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Structure/Line.cpp.o
.PHONY : src/parsing/Config/Structure/Line.cpp.o

src/parsing/Config/Structure/Line.i: src/parsing/Config/Structure/Line.cpp.i
.PHONY : src/parsing/Config/Structure/Line.i

# target to preprocess a source file
src/parsing/Config/Structure/Line.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Structure/Line.cpp.i
.PHONY : src/parsing/Config/Structure/Line.cpp.i

src/parsing/Config/Structure/Line.s: src/parsing/Config/Structure/Line.cpp.s
.PHONY : src/parsing/Config/Structure/Line.s

# target to generate assembly for a file
src/parsing/Config/Structure/Line.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/Structure/Line.cpp.s
.PHONY : src/parsing/Config/Structure/Line.cpp.s

src/parsing/Config/config.o: src/parsing/Config/config.cpp.o
.PHONY : src/parsing/Config/config.o

# target to build an object file
src/parsing/Config/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/config.cpp.o
.PHONY : src/parsing/Config/config.cpp.o

src/parsing/Config/config.i: src/parsing/Config/config.cpp.i
.PHONY : src/parsing/Config/config.i

# target to preprocess a source file
src/parsing/Config/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/config.cpp.i
.PHONY : src/parsing/Config/config.cpp.i

src/parsing/Config/config.s: src/parsing/Config/config.cpp.s
.PHONY : src/parsing/Config/config.s

# target to generate assembly for a file
src/parsing/Config/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Config/config.cpp.s
.PHONY : src/parsing/Config/config.cpp.s

src/parsing/HTTP/Headers/Date.o: src/parsing/HTTP/Headers/Date.cpp.o
.PHONY : src/parsing/HTTP/Headers/Date.o

# target to build an object file
src/parsing/HTTP/Headers/Date.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/HTTP/Headers/Date.cpp.o
.PHONY : src/parsing/HTTP/Headers/Date.cpp.o

src/parsing/HTTP/Headers/Date.i: src/parsing/HTTP/Headers/Date.cpp.i
.PHONY : src/parsing/HTTP/Headers/Date.i

# target to preprocess a source file
src/parsing/HTTP/Headers/Date.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/HTTP/Headers/Date.cpp.i
.PHONY : src/parsing/HTTP/Headers/Date.cpp.i

src/parsing/HTTP/Headers/Date.s: src/parsing/HTTP/Headers/Date.cpp.s
.PHONY : src/parsing/HTTP/Headers/Date.s

# target to generate assembly for a file
src/parsing/HTTP/Headers/Date.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/HTTP/Headers/Date.cpp.s
.PHONY : src/parsing/HTTP/Headers/Date.cpp.s

src/parsing/HTTP/Request.o: src/parsing/HTTP/Request.cpp.o
.PHONY : src/parsing/HTTP/Request.o

# target to build an object file
src/parsing/HTTP/Request.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/HTTP/Request.cpp.o
.PHONY : src/parsing/HTTP/Request.cpp.o

src/parsing/HTTP/Request.i: src/parsing/HTTP/Request.cpp.i
.PHONY : src/parsing/HTTP/Request.i

# target to preprocess a source file
src/parsing/HTTP/Request.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/HTTP/Request.cpp.i
.PHONY : src/parsing/HTTP/Request.cpp.i

src/parsing/HTTP/Request.s: src/parsing/HTTP/Request.cpp.s
.PHONY : src/parsing/HTTP/Request.s

# target to generate assembly for a file
src/parsing/HTTP/Request.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/HTTP/Request.cpp.s
.PHONY : src/parsing/HTTP/Request.cpp.s

src/parsing/HTTP/Request/RequestLine.o: src/parsing/HTTP/Request/RequestLine.cpp.o
.PHONY : src/parsing/HTTP/Request/RequestLine.o

# target to build an object file
src/parsing/HTTP/Request/RequestLine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/HTTP/Request/RequestLine.cpp.o
.PHONY : src/parsing/HTTP/Request/RequestLine.cpp.o

src/parsing/HTTP/Request/RequestLine.i: src/parsing/HTTP/Request/RequestLine.cpp.i
.PHONY : src/parsing/HTTP/Request/RequestLine.i

# target to preprocess a source file
src/parsing/HTTP/Request/RequestLine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/HTTP/Request/RequestLine.cpp.i
.PHONY : src/parsing/HTTP/Request/RequestLine.cpp.i

src/parsing/HTTP/Request/RequestLine.s: src/parsing/HTTP/Request/RequestLine.cpp.s
.PHONY : src/parsing/HTTP/Request/RequestLine.s

# target to generate assembly for a file
src/parsing/HTTP/Request/RequestLine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/HTTP/Request/RequestLine.cpp.s
.PHONY : src/parsing/HTTP/Request/RequestLine.cpp.s

src/parsing/HTTP/Request/RequestTarget/OriginForm.o: src/parsing/HTTP/Request/RequestTarget/OriginForm.cpp.o
.PHONY : src/parsing/HTTP/Request/RequestTarget/OriginForm.o

# target to build an object file
src/parsing/HTTP/Request/RequestTarget/OriginForm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/HTTP/Request/RequestTarget/OriginForm.cpp.o
.PHONY : src/parsing/HTTP/Request/RequestTarget/OriginForm.cpp.o

src/parsing/HTTP/Request/RequestTarget/OriginForm.i: src/parsing/HTTP/Request/RequestTarget/OriginForm.cpp.i
.PHONY : src/parsing/HTTP/Request/RequestTarget/OriginForm.i

# target to preprocess a source file
src/parsing/HTTP/Request/RequestTarget/OriginForm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/HTTP/Request/RequestTarget/OriginForm.cpp.i
.PHONY : src/parsing/HTTP/Request/RequestTarget/OriginForm.cpp.i

src/parsing/HTTP/Request/RequestTarget/OriginForm.s: src/parsing/HTTP/Request/RequestTarget/OriginForm.cpp.s
.PHONY : src/parsing/HTTP/Request/RequestTarget/OriginForm.s

# target to generate assembly for a file
src/parsing/HTTP/Request/RequestTarget/OriginForm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/HTTP/Request/RequestTarget/OriginForm.cpp.s
.PHONY : src/parsing/HTTP/Request/RequestTarget/OriginForm.cpp.s

src/parsing/HTTP/Request/RequestTarget/Scheme.o: src/parsing/HTTP/Request/RequestTarget/Scheme.cpp.o
.PHONY : src/parsing/HTTP/Request/RequestTarget/Scheme.o

# target to build an object file
src/parsing/HTTP/Request/RequestTarget/Scheme.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/HTTP/Request/RequestTarget/Scheme.cpp.o
.PHONY : src/parsing/HTTP/Request/RequestTarget/Scheme.cpp.o

src/parsing/HTTP/Request/RequestTarget/Scheme.i: src/parsing/HTTP/Request/RequestTarget/Scheme.cpp.i
.PHONY : src/parsing/HTTP/Request/RequestTarget/Scheme.i

# target to preprocess a source file
src/parsing/HTTP/Request/RequestTarget/Scheme.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/HTTP/Request/RequestTarget/Scheme.cpp.i
.PHONY : src/parsing/HTTP/Request/RequestTarget/Scheme.cpp.i

src/parsing/HTTP/Request/RequestTarget/Scheme.s: src/parsing/HTTP/Request/RequestTarget/Scheme.cpp.s
.PHONY : src/parsing/HTTP/Request/RequestTarget/Scheme.s

# target to generate assembly for a file
src/parsing/HTTP/Request/RequestTarget/Scheme.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/HTTP/Request/RequestTarget/Scheme.cpp.s
.PHONY : src/parsing/HTTP/Request/RequestTarget/Scheme.cpp.s

src/parsing/HTTP/Request/RequestTarget/Segment.o: src/parsing/HTTP/Request/RequestTarget/Segment.cpp.o
.PHONY : src/parsing/HTTP/Request/RequestTarget/Segment.o

# target to build an object file
src/parsing/HTTP/Request/RequestTarget/Segment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/HTTP/Request/RequestTarget/Segment.cpp.o
.PHONY : src/parsing/HTTP/Request/RequestTarget/Segment.cpp.o

src/parsing/HTTP/Request/RequestTarget/Segment.i: src/parsing/HTTP/Request/RequestTarget/Segment.cpp.i
.PHONY : src/parsing/HTTP/Request/RequestTarget/Segment.i

# target to preprocess a source file
src/parsing/HTTP/Request/RequestTarget/Segment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/HTTP/Request/RequestTarget/Segment.cpp.i
.PHONY : src/parsing/HTTP/Request/RequestTarget/Segment.cpp.i

src/parsing/HTTP/Request/RequestTarget/Segment.s: src/parsing/HTTP/Request/RequestTarget/Segment.cpp.s
.PHONY : src/parsing/HTTP/Request/RequestTarget/Segment.s

# target to generate assembly for a file
src/parsing/HTTP/Request/RequestTarget/Segment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/HTTP/Request/RequestTarget/Segment.cpp.s
.PHONY : src/parsing/HTTP/Request/RequestTarget/Segment.cpp.s

src/parsing/Methods.o: src/parsing/Methods.cpp.o
.PHONY : src/parsing/Methods.o

# target to build an object file
src/parsing/Methods.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Methods.cpp.o
.PHONY : src/parsing/Methods.cpp.o

src/parsing/Methods.i: src/parsing/Methods.cpp.i
.PHONY : src/parsing/Methods.i

# target to preprocess a source file
src/parsing/Methods.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Methods.cpp.i
.PHONY : src/parsing/Methods.cpp.i

src/parsing/Methods.s: src/parsing/Methods.cpp.s
.PHONY : src/parsing/Methods.s

# target to generate assembly for a file
src/parsing/Methods.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Methods.cpp.s
.PHONY : src/parsing/Methods.cpp.s

src/parsing/Tokens.o: src/parsing/Tokens.cpp.o
.PHONY : src/parsing/Tokens.o

# target to build an object file
src/parsing/Tokens.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Tokens.cpp.o
.PHONY : src/parsing/Tokens.cpp.o

src/parsing/Tokens.i: src/parsing/Tokens.cpp.i
.PHONY : src/parsing/Tokens.i

# target to preprocess a source file
src/parsing/Tokens.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Tokens.cpp.i
.PHONY : src/parsing/Tokens.cpp.i

src/parsing/Tokens.s: src/parsing/Tokens.cpp.s
.PHONY : src/parsing/Tokens.s

# target to generate assembly for a file
src/parsing/Tokens.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webserv.dir/build.make CMakeFiles/webserv.dir/src/parsing/Tokens.cpp.s
.PHONY : src/parsing/Tokens.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... webserv"
	@echo "... src/Networking/Client/Client.o"
	@echo "... src/Networking/Client/Client.i"
	@echo "... src/Networking/Client/Client.s"
	@echo "... src/Networking/Response/Response.o"
	@echo "... src/Networking/Response/Response.i"
	@echo "... src/Networking/Response/Response.s"
	@echo "... src/Networking/Response/ResponseHeader.o"
	@echo "... src/Networking/Response/ResponseHeader.i"
	@echo "... src/Networking/Response/ResponseHeader.s"
	@echo "... src/Networking/Server/Server.o"
	@echo "... src/Networking/Server/Server.i"
	@echo "... src/Networking/Server/Server.s"
	@echo "... src/Networking/Sockets/BindingSocket.o"
	@echo "... src/Networking/Sockets/BindingSocket.i"
	@echo "... src/Networking/Sockets/BindingSocket.s"
	@echo "... src/Networking/Sockets/ListeningSocket.o"
	@echo "... src/Networking/Sockets/ListeningSocket.i"
	@echo "... src/Networking/Sockets/ListeningSocket.s"
	@echo "... src/Networking/Sockets/Socket.o"
	@echo "... src/Networking/Sockets/Socket.i"
	@echo "... src/Networking/Sockets/Socket.s"
	@echo "... src/Networking/Status/Status.o"
	@echo "... src/Networking/Status/Status.i"
	@echo "... src/Networking/Status/Status.s"
	@echo "... src/Networking/Utils/utils.o"
	@echo "... src/Networking/Utils/utils.i"
	@echo "... src/Networking/Utils/utils.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parser/Error.o"
	@echo "... src/parser/Error.i"
	@echo "... src/parser/Error.s"
	@echo "... src/parser/bytes/Alpha.o"
	@echo "... src/parser/bytes/Alpha.i"
	@echo "... src/parser/bytes/Alpha.s"
	@echo "... src/parser/bytes/Char.o"
	@echo "... src/parser/bytes/Char.i"
	@echo "... src/parser/bytes/Char.s"
	@echo "... src/parser/bytes/Digit.o"
	@echo "... src/parser/bytes/Digit.i"
	@echo "... src/parser/bytes/Digit.s"
	@echo "... src/parser/bytes/HexChar.o"
	@echo "... src/parser/bytes/HexChar.i"
	@echo "... src/parser/bytes/HexChar.s"
	@echo "... src/parser/bytes/ITag.o"
	@echo "... src/parser/bytes/ITag.i"
	@echo "... src/parser/bytes/ITag.s"
	@echo "... src/parser/bytes/Match.o"
	@echo "... src/parser/bytes/Match.i"
	@echo "... src/parser/bytes/Match.s"
	@echo "... src/parser/bytes/OneOf.o"
	@echo "... src/parser/bytes/OneOf.i"
	@echo "... src/parser/bytes/OneOf.s"
	@echo "... src/parser/bytes/Tag.o"
	@echo "... src/parser/bytes/Tag.i"
	@echo "... src/parser/bytes/Tag.s"
	@echo "... src/parser/bytes/TakeUntil.o"
	@echo "... src/parser/bytes/TakeUntil.i"
	@echo "... src/parser/bytes/TakeUntil.s"
	@echo "... src/parser/bytes/TakeWhile.o"
	@echo "... src/parser/bytes/TakeWhile.i"
	@echo "... src/parser/bytes/TakeWhile.s"
	@echo "... src/parsing/Config/Module/Cgi.o"
	@echo "... src/parsing/Config/Module/Cgi.i"
	@echo "... src/parsing/Config/Module/Cgi.s"
	@echo "... src/parsing/Config/Module/ClientMaxBodySize.o"
	@echo "... src/parsing/Config/Module/ClientMaxBodySize.i"
	@echo "... src/parsing/Config/Module/ClientMaxBodySize.s"
	@echo "... src/parsing/Config/Module/ErrorPage.o"
	@echo "... src/parsing/Config/Module/ErrorPage.i"
	@echo "... src/parsing/Config/Module/ErrorPage.s"
	@echo "... src/parsing/Config/Module/Index.o"
	@echo "... src/parsing/Config/Module/Index.i"
	@echo "... src/parsing/Config/Module/Index.s"
	@echo "... src/parsing/Config/Module/Listen.o"
	@echo "... src/parsing/Config/Module/Listen.i"
	@echo "... src/parsing/Config/Module/Listen.s"
	@echo "... src/parsing/Config/Module/Location.o"
	@echo "... src/parsing/Config/Module/Location.i"
	@echo "... src/parsing/Config/Module/Location.s"
	@echo "... src/parsing/Config/Module/Methods.o"
	@echo "... src/parsing/Config/Module/Methods.i"
	@echo "... src/parsing/Config/Module/Methods.s"
	@echo "... src/parsing/Config/Module/Redirect.o"
	@echo "... src/parsing/Config/Module/Redirect.i"
	@echo "... src/parsing/Config/Module/Redirect.s"
	@echo "... src/parsing/Config/Module/Root.o"
	@echo "... src/parsing/Config/Module/Root.i"
	@echo "... src/parsing/Config/Module/Root.s"
	@echo "... src/parsing/Config/Module/ServerName.o"
	@echo "... src/parsing/Config/Module/ServerName.i"
	@echo "... src/parsing/Config/Module/ServerName.s"
	@echo "... src/parsing/Config/Module/Upload.o"
	@echo "... src/parsing/Config/Module/Upload.i"
	@echo "... src/parsing/Config/Module/Upload.s"
	@echo "... src/parsing/Config/Structure/Line.o"
	@echo "... src/parsing/Config/Structure/Line.i"
	@echo "... src/parsing/Config/Structure/Line.s"
	@echo "... src/parsing/Config/config.o"
	@echo "... src/parsing/Config/config.i"
	@echo "... src/parsing/Config/config.s"
	@echo "... src/parsing/HTTP/Headers/Date.o"
	@echo "... src/parsing/HTTP/Headers/Date.i"
	@echo "... src/parsing/HTTP/Headers/Date.s"
	@echo "... src/parsing/HTTP/Request.o"
	@echo "... src/parsing/HTTP/Request.i"
	@echo "... src/parsing/HTTP/Request.s"
	@echo "... src/parsing/HTTP/Request/RequestLine.o"
	@echo "... src/parsing/HTTP/Request/RequestLine.i"
	@echo "... src/parsing/HTTP/Request/RequestLine.s"
	@echo "... src/parsing/HTTP/Request/RequestTarget/OriginForm.o"
	@echo "... src/parsing/HTTP/Request/RequestTarget/OriginForm.i"
	@echo "... src/parsing/HTTP/Request/RequestTarget/OriginForm.s"
	@echo "... src/parsing/HTTP/Request/RequestTarget/Scheme.o"
	@echo "... src/parsing/HTTP/Request/RequestTarget/Scheme.i"
	@echo "... src/parsing/HTTP/Request/RequestTarget/Scheme.s"
	@echo "... src/parsing/HTTP/Request/RequestTarget/Segment.o"
	@echo "... src/parsing/HTTP/Request/RequestTarget/Segment.i"
	@echo "... src/parsing/HTTP/Request/RequestTarget/Segment.s"
	@echo "... src/parsing/Methods.o"
	@echo "... src/parsing/Methods.i"
	@echo "... src/parsing/Methods.s"
	@echo "... src/parsing/Tokens.o"
	@echo "... src/parsing/Tokens.i"
	@echo "... src/parsing/Tokens.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

